import '@/styles/modern-normalize.css'
import '@/styles/globals.css'

// import type { Metadata } from "next";
import { Geist } from 'next/font/google'

import StyledComponentsRegistry from '@/app/registry'
import { TRPCReactProvider } from '@/trpc/react'
import { SessionProvider } from 'next-auth/react'

import Header from '@/app/_components/Header/Header'

// export const metadata: Metadata = {
// 	title: "Create T3 App",
// 	description: "Generated by create-t3-app",
// 	icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
	subsets: ['latin'],
})

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={geist.className}>
				<StyledComponentsRegistry>
					<SessionProvider>
						<TRPCReactProvider>
							<Header />
							<main className="main">{children}</main>
						</TRPCReactProvider>
					</SessionProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
