import '@/styles/modern-normalize.css'

// import type { Metadata } from "next";
import { Pixelify_Sans } from 'next/font/google'

import StyledComponentsRegistry from '@/app/registry'
import { TRPCReactProvider } from '@/trpc/react'
import { SessionProvider } from 'next-auth/react'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'

import ThemeProvider from '@/styles/ThemeProvider'
import Header from '@/app/_components/Header/Header'

// export const metadata: Metadata = {
// 	title: "Create T3 App",
// 	description: "Generated by create-t3-app",
// 	icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const pixelify = Pixelify_Sans()

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<ThemeProvider>
			<html lang="en">
				<body className={pixelify.className}>
					<StyledComponentsRegistry>
						<NextTopLoader />
						<SessionProvider>
							<TRPCReactProvider>
								<Header />
								<main className="main">{children}</main>
								<Toaster position="bottom-center" reverseOrder={false} />
							</TRPCReactProvider>
						</SessionProvider>
					</StyledComponentsRegistry>
				</body>
			</html>
		</ThemeProvider>
	)
}
